insert into Employees(FirstName, LastName, Role) values('Shmuel', 'Zaltsman', 'Developer')
insert into Employees(FirstName, LastName, Role) values('Ayala', 'Coen', 'Developer Manager')
insert into Employees(FirstName, LastName, Role) values('Miryam', 'Levi', 'Knowlege Manager')
insert into Employees(FirstName, LastName, Role) values('Dina', 'Coen', 'Customer Service')
insert into Employees(FirstName, LastName, Role) values('Lior', 'Dinar', 'IT')
insert into Employees(FirstName, LastName, Role) values('Liran', 'Adinar', 'Developer')
insert into Employees(FirstName, LastName, Role) values('Idan', 'Or', 'Developer')
insert into Employees(FirstName, LastName, Role) values('Mindi', 'Bokovsky', 'Developer')
insert into Employees(FirstName, LastName, Role) values('Minny', 'Somelonglonglongl', 'Manager')
insert into Employees(FirstName, LastName, Role) values('Tali', 'Avram', 'QA')
insert into Employees(FirstName, LastName, Role) values('Tal', 'Istchak', 'QA Manager')
insert into Employees(FirstName, LastName, Role) values('Talya', 'Meshulam', 'Developer')
insert into Employees(FirstName, LastName, Role) values('Tom', 'Bom', 'd')
insert into Employees(FirstName, LastName, Role) values('Simi', 'Bimi', 'I am hiring')

